/* Generated by scripts/stage_assets.py from the pack's video/cut-script.json. Do not edit. */
DATA.cut = {
 "labels": [
  "Cover",
  "Endpoint, not missile",
  "Anatomy",
  "Sensor and shooter",
  "Kill web",
  "Four missions",
  "Layers",
  "Variant roadmap",
  "Evidence ladder",
  "Claims graded",
  "Pressure points",
  "Land and air",
  "Magazine and signals"
 ],
 "slides": [
  "This is the RIM-174, the Standard Missile-6, built by Raytheon. Two notes before we start. The slide gives the dual-thrust motor the Mk 72 designation, but Mk 72 is the booster, which the slide also labels. And the range rings behind the missile are decoration. SM-6's official range is classified, and nothing in this cut puts a number on it. Everything here comes from open sources: DOT&E, the Missile Defense Agency, the Congressional Research Service, and CSIS.",
  "The flawed model says the missile equals the capability. The real equation adds a sensor, a network, and the combat system's compute. Three things follow. Over-the-horizon reach rides on remote sensors and data links. One airframe covers air defense, terminal ballistic-missile defense, and ship strike, with hypersonic defense still in simulation. And each round costs about four point three million then-year dollars and fills a whole launch cell, so it goes to the hard targets.",
  "The part that matters most is the seeker. A semi-active missile needs the ship to keep an illuminator on the target until the end, and a ship has a limited number of illuminators. SM-6's active mode lets the missile find the target itself, so the illuminator is free for the next shot. The warhead is blast-fragmentation, a proximity kill inside the atmosphere. SM-3 is the opposite: hit-to-kill outside it. The slide lists propulsion twice. It is one booster and one dual-thrust motor.",
  "This is NIFC-CA. An E-2D Hawkeye sees past the ship's horizon. CEC moves its track to the ship at fire-control quality. Aegis launches SM-6 toward where the target will be, and the active seeker closes the last stretch. Three gains: you engage earlier, you defend a bigger area, and you can run more engagements at once. Keep the takeaway at the bottom of the slide. Without a valid remote track, the missile's range does not matter.",
  "Here is the same idea as an architecture. Sense is the SPY radars, the E-2D, space sensors, and the Army's LTAMDS. Share is CEC and the Army's IBCS. The slide adds Link 16, which our sources do not cover. Decide is the Aegis weapon system or an Army battery operations center. Act is the Mk 41 launcher, the Army's Typhon, the F/A-18, and the missile. Assess is kill assessment. Share is flagged in orange for a reason: latency or denial there breaks everything downstream.",
  "Four missions, and one correction. The slide marks air warfare and terminal ballistic-missile defense as proven. Read that as demonstrated in tests. The 2016 over-the-horizon intercept and FTM-32 in 2024 are real live intercepts, but DOT&E says FTM-32 was not designed to establish operational effectiveness. Anti-surface is demonstrated, with a blast-fragmentation warhead that damages ships differently from a heavy anti-ship missile. Counter-hypersonic is simulation only so far.",
  "Layers by altitude. SM-3 takes ballistic missiles in midcourse, outside the atmosphere, by hitting them. The Glide Phase Interceptor is a future program for hypersonic weapons in the glide phase. SM-6 is the terminal layer, where geometry and reaction time are hardest. One correction to the bottom row: SM-2 is a medium-to-long-range area-defense missile, not a close-in weapon, and our sources do not cover RAM. ESSM is the real magazine-density option for shorter-range threats.",
  "Read the roadmap on two axes. Along the bottom is the fast lane: Block IA, Dual I adding ballistic defense, Dual II with a software upgrade, and Block IAU replacing obsolete electronics. Each one reuses the airframe. Straight up is Block IB, a bigger motor for more range and speed, and the FY2026 budget put it on strategic pause. Out to the right is AIM-174B, the air-launched version, which drops the surface booster. Expect hardware to move slower than software.",
  "The evidence ladder. A simulated engagement, like FTX-40 or the 2024 Valiant Shield demonstration, shows the sensor and software chain works. A developmental live intercept, like FTM-32, shows the missile can do it under test conditions. Combat use is real, but it rarely comes with clean data, and public Red Sea figures combine SM-2 and SM-6. The top rung, a DOT&E operational test, is still open for the recent ballistic-missile capability. Never jump from rung four to rung six.",
  "Three common claims, graded. Proven against hypersonic missiles is false as stated. FTX-40 was a simulated engagement, and a live intercept such as FTM-43 is not public. A range of 460 kilometers comes from unofficial estimates. The real envelope is classified. Recent intercepts prove full operational effectiveness: DOT&E says FTM-32 was not designed to determine that. In a brief, name the event and the rung, and leave the number out.",
  "The countermeasure picture, kept at the level of broad classes. Pressure on sensors shrinks the over-the-horizon view. Pressure on the network couples sensor and shooter back together. Deception and jamming aim at terminal homing. Complex raids drain magazines, and reloading at sea is constrained, which the slide overstates as no reload at all. The honest bottom line is DOT&E's: there is not enough public data to judge survivability under electronic or cyber attack. Uncertainty, not failure.",
  "Two moves beyond the destroyer. On land, the Army's Typhon puts a vertical launcher in a 40-foot container on a trailer. It deployed to the Philippines in April 2024, and in Talisman Sabre 2025 a ground-launched SM-6 sank a maritime target. That was an exercise target, not a defended warship. In the air, AIM-174B flies on the F/A-18E/F without the surface booster, starting from the jet's speed and position. The Navy says it is deployed. Its range is classified.",
  "Last, economics and signals. One SM-6 fills one cell. ESSM fits up to four in a cell, so cheaper threats should go to cheaper layers. The drone and destroyer prices on the slide are illustrations, not sourced figures, but the point holds: cost-exchange ratios ignore what you protect, and the real limit is cells. Cost depends on its basis: about 2.97 million in constant 2004 dollars, about 4.3 million then-year. Watch three signals: FTM-43, a Block IB decision, and funding for the 540 rounds requested in FY2027."
 ],
 "cards": [
  {
   "question": "Is SM-6 a missile or an endpoint?",
   "detail": "Its reach comes from the sensors and network behind it.",
   "why": "If you credit the missile for reach the network provides, you misjudge both its strength and how it fails.",
   "example": "An SM-6 on a ship whose data link is jammed is the same missile with a much shorter reach."
  },
  {
   "question": "Where did SM-6 come from?",
   "detail": "An SM-2 airframe, an SM-3-family booster and motor, and an AMRAAM-derived seeker.",
   "why": "Reusing proven parts is how the Navy fielded it in 2013 instead of starting from scratch.",
   "example": "The seeker traces back to the AIM-120 AMRAAM, an air-to-air missile."
  },
  {
   "question": "How can a ship hit what its own radar can't see?",
   "detail": "Another sensor holds the track. The missile's seeker finishes.",
   "why": "The Earth curves. A ship's radar cannot see a low-flying threat until it is close.",
   "example": "In 2016, an Aegis cruiser used an airborne sensor's track for the longest-range air-defense intercept in Navy history."
  },
  {
   "question": "What is the weakest link in an SM-6 shot?",
   "detail": "Sense, share, decide, act, assess. Any break bounds the whole.",
   "why": "Every link has to work for the shot to work, so the odds multiply down the chain.",
   "example": "A sound missile fed a stale or wrong track still misses."
  },
  {
   "question": "Which SM-6 missions are actually proven?",
   "detail": "Demonstrated in a test is not the same as proven in operational test.",
   "why": "Briefs often stamp everything proven. The independent tester has not.",
   "example": "Terminal ballistic-missile defense has live intercepts, but DOT&E says those tests did not establish operational effectiveness."
  },
  {
   "question": "Does SM-6 replace SM-3?",
   "detail": "No. Different altitude, different phase, different kill mechanism.",
   "why": "Multi-mission does not mean every layer. Using the wrong layer wastes scarce rounds.",
   "example": "A ballistic missile in midcourse, outside the atmosphere, is SM-3's job. SM-6 gets its chance later, inside the atmosphere."
  },
  {
   "question": "Why is Block IB paused while software upgrades keep shipping?",
   "detail": "A new motor changes the missile. A software change does not.",
   "why": "Kinematic changes bring qualification, thermal, and structural risk that software updates avoid.",
   "example": "Dual II with a software upgrade made a live intercept in 2024. Block IB's larger motor went on strategic pause in the FY2026 budget."
  },
  {
   "question": "How much weight can a test result carry?",
   "detail": "Match each claim to the rung its evidence sits on.",
   "why": "Different events answer different questions. A scripted intercept does not prove combat effectiveness.",
   "example": "FTX-40 tracked a hypersonic-type target, but no missile was fired."
  },
  {
   "question": "Which SM-6 claims fail the check?",
   "detail": "Hypersonic proof, a precise range, and fully operationally effective.",
   "why": "These three show up in briefs and videos all the time, and each one overstates the public record.",
   "example": "Explainer videos quote 460 kilometers. No official source gives a range."
  },
  {
   "question": "Where is the SM-6 system most exposed?",
   "detail": "In the chain around the missile, not the missile alone.",
   "why": "The network that gives SM-6 its reach also gives an adversary more places to push.",
   "example": "Lose the airborne sensor's track, and the engagement falls back to the ship's own radar horizon."
  },
  {
   "question": "What changed when SM-6 left the ship?",
   "detail": "Army Typhon launchers and Navy F/A-18s now carry it.",
   "why": "More launch platforms mean more ways to use it than a destroyer's fixed launch cells allow.",
   "example": "In Talisman Sabre 2025, an Army Typhon fired an SM-6 that sank a maritime target."
  },
  {
   "question": "What should you watch next?",
   "detail": "One live test, one program decision, one budget line.",
   "why": "Each one moves a claim up or down the evidence ladder.",
   "example": "If FTM-43 succeeds, hypersonic defense moves from simulated to live intercept."
  }
 ],
 "open": "Raytheon SM-6, in one sitting. What the missile is, why its reach belongs to the network around it, and which public claims the test record actually supports.",
 "recap": "SM-6 is one missile family with three jobs, and its reach belongs to the kill web: a remote sensor, CEC, Aegis, then the missile's own seeker. It is the terminal layer under SM-3, not a replacement. The live intercepts are real, but DOT&E has not established operational effectiveness, and hypersonic defense is still simulated. Hardware upgrades move slower than software. One round uses one cell, so save it for the targets that need it.",
 "close": "Thank you. If you can name the event behind every claim, and the rung it sits on, you are ready for the room."
};
