"""Render the Raytheon SM-6 vault pack (and NotebookLM exports) into themed HTML pages under library/.

Source of truth stays in Obsidian. Re-run after editing the vault:  python scripts/build_library.py
Writes library/*.html and library/manifest.json + manifest.js (read by index.html's Library view).
"""
import csv
import html
import io
import json
import re
from pathlib import Path

import markdown
import yaml

SITE = Path(__file__).resolve().parent.parent
LIB = SITE / "library"
VAULT = Path(r"C:\obsidian\personal_research_2026")
PACK = VAULT / "Learning" / "one-day-mastery" / "sm-6"
WEAPONS = VAULT / "Learning" / "Weapons"
EXP = PACK / "notebooklm" / "exports"
OUT = Path(r"C:\output\obsidian\notebooklm\odm-sm-6")

NBLM_CAVEAT = (
    "Generated by NotebookLM from the pack's sources (the spine page, the source ledger, the blocks, and the "
    "ledger's videos). The spine page and the pack notes win where they differ. Known issues: illustrative figures "
    "(a $2,000 drone, a ~$2 billion destroyer, \"300 crew\", \"$2M to $4M\" rounds) are not in the ledger; the "
    "explanation of the $28.7 million Red Sea figure as salvo arithmetic is NotebookLM's inference; Link 16 and "
    "the 100 km atmosphere boundary are general knowledge, not ledger sources; the ~$4.3M then-year cost comes "
    "from budget analysis [S29], not the FY2025 budget document itself [S25]; the decision packet's \"by FY2027\" "
    "depletion warning is a projection. Bracketed numbers like [1] refer to NotebookLM's own source list, not S#."
)

SPINE = WEAPONS / "SM-6" / "SM-6 - Capabilities, Architecture, and Countermeasure Assessment.md"

# (slug, source path, section, title override or None, nblm?)
PAGES = [
    ("spine", SPINE, "Spine", "SM-6: capabilities, architecture, and countermeasure assessment", False),
    ("weapons-hub", WEAPONS / "00 - Weapons Learning Hub.md", "Spine", "Weapons learning hub", False),
    ("hub", PACK / "00 - Raytheon SM-6 Hub.md", "Plan", "Raytheon SM-6 one-day mastery hub", False),
    ("mission", PACK / "MISSION.md", "Plan", None, False),
    ("intake-record", PACK / "intake" / "2026-10-04 - Intake.md", "Plan", "Intake record", False),
    ("day-plan", PACK / "day-plan.md", "Plan", None, False),
    *[(f"block-{p.stem}", p, "Day blocks", None, False) for p in sorted((PACK / "blocks").glob("*.md"))],
    ("glossary", PACK / "GLOSSARY.md", "Reference", None, False),
    ("cheatsheet", PACK / "reference" / "cheatsheet.md", "Reference", None, False),
    ("decision-card", PACK / "reference" / "decision-card.md", "Reference", "Decision card: reading an SM-6 claim", False),
    ("quiz-bank", PACK / "reference" / "quiz-bank.md", "Reference", None, False),
    ("source-ledger", PACK / "reference" / "source-ledger.md", "Reference", None, False),
    ("resources", PACK / "RESOURCES.md", "Reference", None, False),
    ("elicit", PACK / "reference" / "elicit-light-research.md", "Reference", "Elicit light research", False),
    ("prompt-library", PACK / "prompts" / "00 - Prompt Library.md", "Prompts", None, False),
    ("prompts-all", PACK / "prompts" / "notebooklm-all-prompts.md", "Prompts", "All NotebookLM prompts (archive)", False),
    ("prompts-tailored", PACK / "prompts" / "tailored-prompts.md", "Prompts", None, False),
    ("prompts-notebooklm-set", PACK / "prompts" / "notebooklm-prompt-set.md", "Prompts", None, False),
    ("prompts-decision-packet", PACK / "prompts" / "notebooklm-room-craft-decision-packet.md", "Prompts", None, False),
    ("nblm-briefing", EXP / "Raytheon Standard Missile-6 (SM-6)_ Comprehensive System Briefing.md", "NotebookLM reports", "Comprehensive system briefing", True),
    ("nblm-study-guide", EXP / "Comprehensive Study Guide_ Raytheon Standard Missile-6 (SM-6) Architecture, Capa.md", "NotebookLM reports", "Comprehensive study guide", True),
    ("nblm-practitioner", EXP / "Raytheon SM-6 Practitioner Briefing_ System Architecture, Core Vocabulary, and C.md", "NotebookLM reports", "Practitioner briefing: architecture and vocabulary (T1)", True),
    ("nblm-mental-models", EXP / "Raytheon SM-6_ Core Mental Models, Architectural Distinctions, and Analytical Fa.md", "NotebookLM reports", "Mental models and distinctions (T2)", True),
    ("nblm-claims-playbook", EXP / "Practice Playbook for Grading Public Claims_ Raytheon Standard Missile-6 (SM-6).md", "NotebookLM reports", "Playbook for grading public claims (T3)", True),
    ("nblm-trap-matrix", EXP / "Analytical Trap Matrix & Edge-Case Catalog_ Raytheon SM-6 (RIM-174).md", "NotebookLM reports", "Analytical trap matrix (T4)", True),
    ("nblm-decision-packet", EXP / "Executive Decision Packet_ Raytheon Standard Missile-6 (SM-6) Investment & Deplo.md", "NotebookLM reports", "Executive decision packet (T5)", True),
    ("nblm-claims-table", EXP / "Raytheon SM-6 Major Claims Assessment.csv", "NotebookLM reports", "Major claims assessment (data table)", True),
    ("media-deep-dive-cut", PACK / "Deep Dive Cut.md", "Media", "Deep dive cut", False),
    ("media-cut-script", PACK / "video" / "cut-script.json", "Media", "Deep dive cut script (narration, question cards, corrections)", False),
    ("media-slides", PACK / "Presentation slides.md", "Media", "Presentation slides", False),
    ("media-shorts-plan", PACK / "prompts" / "shorts-topics.json", "Media", "Shorts plan", False),
    ("pipeline-suite", PACK / "notebooklm" / "00 - Suite.md", "Pipeline", "NotebookLM suite", False),
    ("pipeline-inventory", PACK / "notebooklm" / "01 - Download Inventory.md", "Pipeline", "NotebookLM download inventory", False),
    ("pipeline-run-record", OUT / "odm-sm-6__2026-10-05__notebooklm.json", "Pipeline", "NotebookLM run record", False),
    *[(f"source-{p.stem}", p, "NotebookLM source bundle", f"Source as uploaded: {p.stem}", False)
      for p in sorted((OUT / "sources").glob("*.md")) if p.stem != "01-mindmap"],
]

# Vault notes whose content lives on a console view rather than a library page.
CONSOLE_LINKS = {"Deep Dive Cut": "deck", "Presentation slides": "deck", "shorts-topics": "shorts", "mindmap": None}


def load_sources():
    rows = {}
    text = (PACK / "reference" / "source-ledger.md").read_text(encoding="utf-8")
    for m in re.finditer(r"^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*(https?://\S+?)\s*\|", text, re.M):
        rows[int(m.group(1))] = (m.group(2), m.group(3))
    return rows


SOURCES = load_sources()


def split_frontmatter(text):
    text = text.lstrip("\ufeff")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            try:
                fm = yaml.safe_load(text[3:end]) or {}
            except yaml.YAMLError:
                fm = {}
            return fm, text[end + 4:]
    return {}, text


def slug_for_target(target):
    t = target.split("|")[0].split("#")[0].strip().replace("\\", "/")
    name = t.rsplit("/", 1)[-1].removesuffix(".md")
    if name == "mindmap":
        return "spine"
    for slug, path, *_ in PAGES:
        if path.stem == name:
            return slug
    return None


def convert_obsidian(md):
    md = re.sub(r"\$\[(S[^\]]+)\]\$", r"[\1]", md)  # NotebookLM $[S1]$ citations

    def embed(m):
        target = m.group(1).split("|")[0].strip()
        if target.lower().endswith((".png", ".jpg", ".jpeg", ".gif", ".svg")):
            name = target.rsplit("/", 1)[-1]
            m_sl = re.fullmatch(r"(?i)slide(\d+)\.jpe?g", name)
            if m_sl:
                name = f"slide-{int(m_sl.group(1)):02d}.jpg"
            return f'<a href="../assets/slides/{name}" target="_blank"><img class="embed" src="../assets/slides/{name}" alt="{html.escape(name)}"></a>'
        return ""
    md = re.sub(r"!\[\[([^\]]+)\]\]", embed, md)

    def wikilink(m):
        inner = m.group(1).replace("\\|", "|")
        label = inner.split("|", 1)[1] if "|" in inner else inner.split("/")[-1].removesuffix(".md")
        slug = slug_for_target(inner)
        if slug:
            return f"[{label}]({slug}.html)"
        stem = inner.split("|")[0].split("/")[-1].removesuffix(".md")
        if CONSOLE_LINKS.get(stem):
            return f"[{label}](../index.html#/{CONSOLE_LINKS[stem]})"
        return f"*{label}*"
    md = re.sub(r"\[\[([^\]]+)\]\]", wikilink, md)

    # Obsidian callouts -> html blocks
    out, lines, i = [], md.split("\n"), 0
    while i < len(lines):
        m = re.match(r"^>\s*\[!(\w+)\]([-+]?)\s*(.*)$", lines[i])
        if m:
            kind, title = m.group(1).lower(), m.group(3) or m.group(1).title()
            body = []
            i += 1
            while i < len(lines) and lines[i].startswith(">"):
                body.append(re.sub(r"^>\s?", "", lines[i]))
                i += 1
            inner = markdown.markdown("\n".join(body), extensions=["tables", "fenced_code", "sane_lists"])
            out.append(f'<div class="callout {kind}" markdown="0"><div class="callout-title">{html.escape(title)}</div>{inner}</div>\n')
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def link_citations(h):
    def one(sid):
        n = int(sid[1:])
        if n in SOURCES:
            t, u = SOURCES[n]
            return f'<a class="cite" href="{html.escape(u)}" target="_blank" rel="noopener" title="{html.escape(t)}">{sid}</a>'
        return sid

    def repl(m):
        parts = re.split(r"(\s*,\s*)", m.group(1))
        return "[" + "".join(one(p) if re.fullmatch(r"S\d+", p) else p for p in parts) + "]"
    return re.sub(r"\[((?:S\d+)(?:\s*,\s*S\d+)*)\]", repl, h)


def render_md(text):
    fm, body = split_frontmatter(text)
    body = re.sub(r"^\*\*Location:\*\*.*$", "", body, flags=re.M)
    body = re.sub(r"%%.*?%%", "", body, flags=re.S)  # Obsidian comments
    body = convert_obsidian(body)
    body = re.sub(r"```mermaid\n(.*?)```", lambda m: f'<pre class="mermaid">{html.escape(m.group(1))}</pre>', body, flags=re.S)
    h = markdown.markdown(body, extensions=["tables", "fenced_code", "sane_lists", "md_in_html", "footnotes"])
    h = re.sub(r"<li>\[ \]", '<li class="task"><input type="checkbox" disabled>', h)
    h = re.sub(r"<li>\[x\]", '<li class="task"><input type="checkbox" checked disabled>', h)
    return fm, link_citations(h)


def render_csv(text):
    rows = list(csv.reader(io.StringIO(text.lstrip("\ufeff"))))
    head, body = rows[0], rows[1:]
    t = "<table><thead><tr>" + "".join(f"<th>{html.escape(c)}</th>" for c in head) + "</tr></thead><tbody>"
    for r in body:
        t += "<tr>" + "".join(f"<td>{html.escape(c)}</td>" for c in r) + "</tr>"
    return {"description": f"{len(body)} claims NotebookLM extracted from the notebook, with layer, implication, support level, and what the sources leave out."}, t + "</tbody></table>"


def render_cut_script(text):
    d = json.loads(text)
    cards, labels = d.get("cards", []), d.get("labels", [])
    h = f"<p><b>Opening.</b> {html.escape(d.get('open', ''))}</p>"
    for i, line in enumerate(d.get("slides", []), 1):
        n = f"{i:02d}"
        label = labels[i - 1] if i - 1 < len(labels) else ""
        h += f"<h2>Slide {i}: {html.escape(label)}</h2>"
        c = cards[i - 2] if 2 <= i and i - 2 < len(cards) else None
        if c:
            h += (f'<div class="callout question"><div class="callout-title">Question card: {html.escape(c["question"])}</div>'
                  f'<p><b>{html.escape(c["detail"])}</b> {html.escape(c["why"])}</p><p><i>Example:</i> {html.escape(c["example"])}</p></div>')
        h += f'<a href="../assets/slides/slide-{n}.jpg" target="_blank"><img class="embed" src="../assets/slides/slide-{n}.jpg" alt="Slide {i}" loading="lazy"></a>'
        h += f"<p>{html.escape(line)}</p>"
    h += f"<h2>Recap</h2><p>{html.escape(d.get('recap', ''))}</p><h2>Close</h2><p>{html.escape(d.get('close', ''))}</p>"
    fixes = d.get("corrections") or []
    if fixes:
        h += '<div class="callout warning"><div class="callout-title">Slide errors corrected in the narration</div><ul>' + \
             "".join(f"<li>{html.escape(f)}</li>" for f in fixes) + "</ul></div>"
    h += '<p>Watch the cut on the <a href="../index.html#/deck">Deck and deep-dive cut</a> page.</p>'
    return {"description": "Every narration line and question card from the deep-dive cut, with the slide it belongs to and the slide errors it corrects."}, h


def render_shorts_plan(text):
    plan = json.loads(text)
    site = json.loads((SITE / "shorts-catalog.json").read_text(encoding="utf-8"))
    mp = EXP / "shorts-manifest.json"
    made = json.loads(mp.read_text(encoding="utf-8-sig")) if mp.exists() else []
    ids = {m.get("name"): m.get("artifact_id", "") for m in made}
    h = f"<p>{html.escape(plan.get('note', ''))}</p><h2>Planned shorts (NotebookLM prompts)</h2>"
    h += "<table><thead><tr><th>#</th><th>Planned title</th><th>One job (prompt focus)</th><th>NotebookLM artifact</th></tr></thead><tbody>"
    for i, it in enumerate(plan.get("items", []), 1):
        h += f"<tr><td>{i}</td><td>{html.escape(it['title'])}</td><td>{html.escape(it['focus'])}</td><td><code>{html.escape(ids.get(it['name'], ''))}</code></td></tr>"
    h += "</tbody></table><h2>Published shorts</h2><p>NotebookLM titled the finished videos itself, so the titles differ from the planned ones.</p>"
    h += "<table><thead><tr><th>Short</th><th>Family</th><th>Length</th><th>Watch</th></tr></thead><tbody>"
    for it in site.get("items", []):
        h += f"<tr><td>{html.escape(it['title'])}</td><td>{html.escape(it.get('pillar', ''))}</td><td>{it.get('duration', '')} s</td><td><a href=\"../index.html#/shorts/{it['id']}\">On the site</a></td></tr>"
    h += "</tbody></table>"
    return {"description": "The six planned shorts with their one-job prompts, and the published videos."}, h


def render_json_record(text):
    d = json.loads(text)

    def row(k, v):
        v = "<pre>" + html.escape(json.dumps(v, indent=2, ensure_ascii=False)) + "</pre>" if isinstance(v, (dict, list)) else html.escape(str(v))
        return f"<tr><th>{html.escape(str(k))}</th><td>{v}</td></tr>"
    body = "<table><tbody>" + "".join(row(k, v) for k, v in d.items()) + "</tbody></table>"
    return {"description": "Machine-readable record of the NotebookLM W8 run for this pack."}, body


PAGE_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} | Learn SM-6</title>
<meta name="description" content="{desc}">
<link rel="icon" href="../assets/icons/icon-192.png" type="image/png">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="library.css">
<script>try{{var p=JSON.parse(localStorage.getItem("appPalette"))||"github",m=JSON.parse(localStorage.getItem("appMode"))||"dark";document.documentElement.setAttribute("data-theme",p+"-"+m);}}catch(e){{document.documentElement.setAttribute("data-theme","github-dark");}}</script>
</head>
<body>
<header class="topbar">
  <a href="../index.html" class="home">&larr; Learn SM-6 console</a>
  <span class="crumb">Library · {section}</span>
  <a href="index.html" class="home">All pages</a>
</header>
<main class="doc">
  <div class="kicker">{section}</div>
  <h1 class="doctitle">{title}</h1>
  {descblock}
  {caveat}
  <article>{body}</article>
  <footer class="docfoot">
    Rendered from <code>{source}</code>. The Obsidian vault is the source of truth. Open sources only; study material. Citations <span class="cite">S#</span> link to the pack's source ledger.
    {prevnext}
  </footer>
</main>
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
const dark=(document.documentElement.getAttribute("data-theme")||"").endsWith("dark");
mermaid.initialize({{startOnLoad:true,theme:dark?"dark":"default",securityLevel:"strict"}});
</script>
</body>
</html>
"""


def main():
    LIB.mkdir(exist_ok=True)
    manifest = []
    for idx, (slug, path, section, title, nblm) in enumerate(PAGES):
        text = path.read_text(encoding="utf-8-sig")
        if path.suffix == ".csv":
            fm, body = render_csv(text)
        elif path.name == "cut-script.json":
            fm, body = render_cut_script(text)
        elif path.name == "shorts-topics.json":
            fm, body = render_shorts_plan(text)
        elif path.name.endswith("__notebooklm.json"):
            fm, body = render_json_record(text)
        else:
            fm, body = render_md(text)
        h1 = re.search(r"<h1>(.*?)</h1>", body)
        page_title = title or (re.sub("<.*?>", "", h1.group(1)) if h1 else path.stem)
        if h1:
            body = body.replace(h1.group(0), "", 1)
        desc = str(fm.get("description", "")) if fm else ""
        caveat = f'<div class="callout warning"><div class="callout-title">NotebookLM output — read with the spine page</div><p>{link_citations(html.escape(NBLM_CAVEAT))}</p></div>' if nblm else ""
        prev_ = PAGES[idx - 1] if idx > 0 and PAGES[idx - 1][2] == section else None
        next_ = PAGES[idx + 1] if idx + 1 < len(PAGES) and PAGES[idx + 1][2] == section else None
        pn = ""
        if prev_ or next_:
            pn = '<div class="prevnext">' + (f'<a href="{prev_[0]}.html">&larr; Previous</a>' if prev_ else "<span></span>") + \
                 (f'<a href="{next_[0]}.html">Next &rarr;</a>' if next_ else "<span></span>") + "</div>"
        src_rel = str(path.relative_to(VAULT)) if VAULT in path.parents else str(path)
        (LIB / f"{slug}.html").write_text(PAGE_TMPL.format(
            title=html.escape(page_title), desc=html.escape(desc), section=html.escape(section),
            descblock=f'<p class="lead">{html.escape(desc)}</p>' if desc else "", caveat=caveat,
            body=body, source=html.escape(src_rel), prevnext=pn), encoding="utf-8")
        manifest.append({"slug": slug, "title": page_title, "section": section, "desc": desc, "nblm": nblm})

    sections = {}
    for m in manifest:
        sections.setdefault(m["section"], []).append(m)
    idx_body = ""
    for sec, items in sections.items():
        idx_body += f"<h2>{html.escape(sec)}</h2><ul class='pagelist'>" + "".join(
            f'<li><a href="{m["slug"]}.html">{html.escape(m["title"])}</a>' +
            (f' <span class="muted">— {html.escape(m["desc"])}</span>' if m["desc"] else "") + "</li>" for m in items) + "</ul>"
    (LIB / "index.html").write_text(PAGE_TMPL.format(
        title="Library", desc="Every SM-6 study note rendered as a web page.", section="Index",
        descblock=f'<p class="lead">{len(manifest)} pages rendered from the Weapons spine page, the one-day pack, and the NotebookLM exports.</p>',
        caveat="", body=idx_body, source="Learning/one-day-mastery/sm-6/", prevnext=""), encoding="utf-8")
    (LIB / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    (LIB / "manifest.js").write_text("window.LIBRARY = " + json.dumps(manifest) + ";\n", encoding="utf-8")
    print(f"built {len(manifest)} pages + index; {len(SOURCES)} sources linked")


if __name__ == "__main__":
    main()
